project_id = "hcyikjzgzhjjthyxrypd"

[functions.create-user]
verify_jwt = false

[functions.seed-demo-data]
verify_jwt = false

[functions.auth-cpf]
verify_jwt = false

[functions.calculate-daily-indicators]
verify_jwt = false

[functions.calculate-monthly-bonus]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.calculate-caixas-batidas]
verify_jwt = false

[functions.auth-email]
verify_jwt = false
